# Change these first
owner: archem-team # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: PepChat
    url: https://peptide.chat

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.peptide.chat
  # baseUrl: /your-repo-name
  logoUrl: https://peptide.chat/assets/logo_round.png
  name: PepChat Status
  introTitle: "Status of PepChat services. ::CLOUDFLARE_ERROR_500S_BOX::"
  introMessage: Status details may not always be accurate.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: PepChat
      href: https://peptide.chat

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
